name: CI - Go Notes

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: CHECKOUT DO CODIGO
        uses: actions/checkout@v4
        
      - name: CONFIGURAR O GO
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          
      - name: COMPILAR
        run: go build ./...
        working-directory: app
        
      - name: EXECUTAR
        run: go test ./...
        working-directory: app
